{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "50fd51de-cd84-4bd6-8380-062ba64dc110",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🎉 Generando página de Stitch...\n",
      "✅ Archivo creado: C:\\Users\\jhoel\\stitch_love.html\n",
      "🌐 Abriendo en el navegador...\n",
      "Servidor iniciado en http://localhost:8000\n",
      "\n",
      "📱 Para compartir por WhatsApp:\n",
      "1. La página se abrirá automáticamente en tu navegador\n",
      "2. Copia la URL: http://localhost:8000/stitch_love.html\n",
      "3. Comparte esta URL por WhatsApp\n",
      "\n",
      "⚠️  IMPORTANTE: El servidor debe estar ejecutándose para que funcione\n",
      "💡 Presiona Ctrl+C para detener el servidor\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [17/Jul/2025 17:25:06] \"GET /stitch_love.html HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jul/2025 17:25:09] code 404, message File not found\n",
      "127.0.0.1 - - [17/Jul/2025 17:25:09] \"GET /favicon.ico HTTP/1.1\" 404 -\n",
      "127.0.0.1 - - [17/Jul/2025 17:26:54] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jul/2025 17:27:38] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jul/2025 17:27:56] \"GET /stitch_love.html HTTP/1.1\" 304 -\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import webbrowser\n",
    "from http.server import HTTPServer, SimpleHTTPRequestHandler\n",
    "import threading\n",
    "\n",
    "def crear_pagina_stitch():\n",
    "    \"\"\"Crea el archivo HTML con la página de Stitch\"\"\"\n",
    "    \n",
    "    html_content = \"\"\"\n",
    "    <!DOCTYPE html>\n",
    "    <html lang=\"es\">\n",
    "    <head>\n",
    "        <meta charset=\"UTF-8\">\n",
    "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
    "        <title>¿Me amas? - Stitch</title>\n",
    "        <style>\n",
    "            body {\n",
    "                font-family: 'Arial', sans-serif;\n",
    "                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n",
    "                margin: 0;\n",
    "                padding: 0;\n",
    "                min-height: 100vh;\n",
    "                display: flex;\n",
    "                flex-direction: column;\n",
    "                justify-content: center;\n",
    "                align-items: center;\n",
    "                overflow-x: hidden;\n",
    "            }\n",
    "            \n",
    "            .container {\n",
    "                text-align: center;\n",
    "                background: rgba(255, 255, 255, 0.1);\n",
    "                border-radius: 20px;\n",
    "                padding: 40px;\n",
    "                box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3);\n",
    "                backdrop-filter: blur(10px);\n",
    "                border: 1px solid rgba(255, 255, 255, 0.2);\n",
    "            }\n",
    "            \n",
    "            .stitch-image {\n",
    "                width: 200px;\n",
    "                height: 200px;\n",
    "                margin: 20px auto;\n",
    "                background: url('data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 200 200\"><circle cx=\"100\" cy=\"100\" r=\"80\" fill=\"%23006bb3\"/><circle cx=\"80\" cy=\"80\" r=\"15\" fill=\"black\"/><circle cx=\"120\" cy=\"80\" r=\"15\" fill=\"black\"/><ellipse cx=\"100\" cy=\"120\" rx=\"20\" ry=\"10\" fill=\"black\"/><path d=\"M60 60 Q100 40 140 60\" stroke=\"black\" stroke-width=\"3\" fill=\"none\"/><path d=\"M60 140 Q100 160 140 140\" stroke=\"black\" stroke-width=\"3\" fill=\"none\"/></svg>') no-repeat center;\n",
    "                background-size: contain;\n",
    "                animation: bounce 2s infinite;\n",
    "            }\n",
    "            \n",
    "            .question {\n",
    "                font-size: 2.5em;\n",
    "                color: white;\n",
    "                margin: 30px 0;\n",
    "                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);\n",
    "                font-weight: bold;\n",
    "            }\n",
    "            \n",
    "            .buttons-container {\n",
    "                display: flex;\n",
    "                gap: 30px;\n",
    "                justify-content: center;\n",
    "                margin-top: 30px;\n",
    "                position: relative;\n",
    "                height: 80px;\n",
    "            }\n",
    "            \n",
    "            .btn {\n",
    "                padding: 15px 30px;\n",
    "                font-size: 1.2em;\n",
    "                font-weight: bold;\n",
    "                border: none;\n",
    "                border-radius: 25px;\n",
    "                cursor: pointer;\n",
    "                transition: all 0.3s ease;\n",
    "                box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);\n",
    "                position: relative;\n",
    "            }\n",
    "            \n",
    "            .btn-si {\n",
    "                background: linear-gradient(45deg, #ff6b6b, #ff8e8e);\n",
    "                color: white;\n",
    "            }\n",
    "            \n",
    "            .btn-si:hover {\n",
    "                transform: scale(1.1);\n",
    "                box-shadow: 0 8px 25px rgba(255, 107, 107, 0.4);\n",
    "            }\n",
    "            \n",
    "            .btn-no {\n",
    "                background: linear-gradient(45deg, #4ecdc4, #6dd5ed);\n",
    "                color: white;\n",
    "                transition: all 0.3s ease;\n",
    "            }\n",
    "            \n",
    "            .btn-no:hover {\n",
    "                transform: scale(1.05);\n",
    "            }\n",
    "            \n",
    "            .celebration {\n",
    "                display: none;\n",
    "                position: fixed;\n",
    "                top: 0;\n",
    "                left: 0;\n",
    "                width: 100%;\n",
    "                height: 100%;\n",
    "                background: rgba(255, 20, 147, 0.9);\n",
    "                z-index: 1000;\n",
    "                justify-content: center;\n",
    "                align-items: center;\n",
    "                flex-direction: column;\n",
    "            }\n",
    "            \n",
    "            .celebration h1 {\n",
    "                font-size: 4em;\n",
    "                color: white;\n",
    "                margin-bottom: 20px;\n",
    "                animation: pulse 1s infinite;\n",
    "            }\n",
    "            \n",
    "            .heart {\n",
    "                font-size: 3em;\n",
    "                color: red;\n",
    "                animation: heartbeat 1s infinite;\n",
    "            }\n",
    "            \n",
    "            @keyframes bounce {\n",
    "                0%, 100% { transform: translateY(0); }\n",
    "                50% { transform: translateY(-10px); }\n",
    "            }\n",
    "            \n",
    "            @keyframes pulse {\n",
    "                0%, 100% { transform: scale(1); }\n",
    "                50% { transform: scale(1.1); }\n",
    "            }\n",
    "            \n",
    "            @keyframes heartbeat {\n",
    "                0%, 100% { transform: scale(1); }\n",
    "                50% { transform: scale(1.3); }\n",
    "            }\n",
    "            \n",
    "            .floating-hearts {\n",
    "                position: absolute;\n",
    "                top: 0;\n",
    "                left: 0;\n",
    "                width: 100%;\n",
    "                height: 100%;\n",
    "                pointer-events: none;\n",
    "                overflow: hidden;\n",
    "            }\n",
    "            \n",
    "            .floating-heart {\n",
    "                position: absolute;\n",
    "                font-size: 2em;\n",
    "                color: red;\n",
    "                animation: floatUp 3s linear infinite;\n",
    "            }\n",
    "            \n",
    "            @keyframes floatUp {\n",
    "                0% {\n",
    "                    transform: translateY(100vh) rotate(0deg);\n",
    "                    opacity: 1;\n",
    "                }\n",
    "                100% {\n",
    "                    transform: translateY(-100px) rotate(360deg);\n",
    "                    opacity: 0;\n",
    "                }\n",
    "            }\n",
    "        </style>\n",
    "    </head>\n",
    "    <body>\n",
    "        <div class=\"container\">\n",
    "            <div class=\"stitch-image\"></div>\n",
    "            <div class=\"question\">¿Me amas?</div>\n",
    "            <div class=\"buttons-container\">\n",
    "                <button class=\"btn btn-si\" onclick=\"respuestaSi()\">Sí ❤️</button>\n",
    "                <button class=\"btn btn-no\" id=\"btnNo\" onclick=\"respuestaNo()\">No 💔</button>\n",
    "            </div>\n",
    "        </div>\n",
    "        \n",
    "        <div class=\"celebration\" id=\"celebration\">\n",
    "            <h1>¡Sabía que me amabas! 💕</h1>\n",
    "            <div class=\"heart\">❤️💙💜💚💛</div>\n",
    "            <div class=\"floating-hearts\" id=\"floatingHearts\"></div>\n",
    "        </div>\n",
    "        \n",
    "        <script>\n",
    "            const btnNo = document.getElementById('btnNo');\n",
    "            let moveCount = 0;\n",
    "            \n",
    "            // Función para mover el botón \"No\"\n",
    "            function moverBotonNo() {\n",
    "                const container = document.querySelector('.buttons-container');\n",
    "                const containerRect = container.getBoundingClientRect();\n",
    "                \n",
    "                // Generar posición aleatoria dentro del contenedor\n",
    "                const maxX = containerRect.width - btnNo.offsetWidth;\n",
    "                const maxY = containerRect.height - btnNo.offsetHeight;\n",
    "                \n",
    "                const newX = Math.random() * maxX;\n",
    "                const newY = Math.random() * maxY;\n",
    "                \n",
    "                btnNo.style.position = 'absolute';\n",
    "                btnNo.style.left = newX + 'px';\n",
    "                btnNo.style.top = newY + 'px';\n",
    "                \n",
    "                moveCount++;\n",
    "                \n",
    "                // Después de varios movimientos, hacer el botón más pequeño\n",
    "                if (moveCount > 3) {\n",
    "                    btnNo.style.transform = 'scale(0.8)';\n",
    "                    btnNo.innerHTML = 'No 😢';\n",
    "                }\n",
    "                \n",
    "                if (moveCount > 6) {\n",
    "                    btnNo.style.transform = 'scale(0.6)';\n",
    "                    btnNo.innerHTML = 'No... 😭';\n",
    "                }\n",
    "            }\n",
    "            \n",
    "            // Agregar evento de hover al botón \"No\"\n",
    "            btnNo.addEventListener('mouseenter', moverBotonNo);\n",
    "            btnNo.addEventListener('touchstart', moverBotonNo);\n",
    "            \n",
    "            function respuestaSi() {\n",
    "                document.getElementById('celebration').style.display = 'flex';\n",
    "                crearCorazonesFlotantes();\n",
    "                \n",
    "                // Reproducir sonido de celebración (opcional)\n",
    "                // new Audio('data:audio/wav;base64,...').play();\n",
    "            }\n",
    "            \n",
    "            function respuestaNo() {\n",
    "                // Mover el botón cuando se intente hacer click\n",
    "                moverBotonNo();\n",
    "                \n",
    "                // Mostrar mensaje gracioso\n",
    "                setTimeout(() => {\n",
    "                    alert('¡No puedes escapar de mi amor! 💕');\n",
    "                }, 500);\n",
    "            }\n",
    "            \n",
    "            function crearCorazonesFlotantes() {\n",
    "                const container = document.getElementById('floatingHearts');\n",
    "                const hearts = ['❤️', '💙', '💜', '💚', '💛', '🧡', '💕', '💖'];\n",
    "                \n",
    "                setInterval(() => {\n",
    "                    const heart = document.createElement('div');\n",
    "                    heart.className = 'floating-heart';\n",
    "                    heart.innerHTML = hearts[Math.floor(Math.random() * hearts.length)];\n",
    "                    heart.style.left = Math.random() * 100 + '%';\n",
    "                    heart.style.animationDelay = Math.random() * 2 + 's';\n",
    "                    \n",
    "                    container.appendChild(heart);\n",
    "                    \n",
    "                    // Eliminar el corazón después de la animación\n",
    "                    setTimeout(() => {\n",
    "                        heart.remove();\n",
    "                    }, 3000);\n",
    "                }, 300);\n",
    "            }\n",
    "        </script>\n",
    "    </body>\n",
    "    </html>\n",
    "    \"\"\"\n",
    "    \n",
    "    # Crear el archivo HTML\n",
    "    with open('stitch_love.html', 'w', encoding='utf-8') as f:\n",
    "        f.write(html_content)\n",
    "    \n",
    "    return os.path.abspath('stitch_love.html')\n",
    "\n",
    "def iniciar_servidor():\n",
    "    \"\"\"Inicia un servidor HTTP local para servir la página\"\"\"\n",
    "    class CustomHandler(SimpleHTTPRequestHandler):\n",
    "        def __init__(self, *args, **kwargs):\n",
    "            super().__init__(*args, directory=os.getcwd(), **kwargs)\n",
    "    \n",
    "    server = HTTPServer(('localhost', 8000), CustomHandler)\n",
    "    print(\"Servidor iniciado en http://localhost:8000\")\n",
    "    server.serve_forever()\n",
    "\n",
    "def main():\n",
    "    \"\"\"Función principal\"\"\"\n",
    "    print(\"🎉 Generando página de Stitch...\")\n",
    "    \n",
    "    # Crear la página HTML\n",
    "    archivo_html = crear_pagina_stitch()\n",
    "    print(f\"✅ Archivo creado: {archivo_html}\")\n",
    "    \n",
    "    # Iniciar servidor en un hilo separado\n",
    "    servidor_thread = threading.Thread(target=iniciar_servidor, daemon=True)\n",
    "    servidor_thread.start()\n",
    "    \n",
    "    # Abrir la página en el navegador\n",
    "    print(\"🌐 Abriendo en el navegador...\")\n",
    "    webbrowser.open('http://localhost:8000/stitch_love.html')\n",
    "    \n",
    "    print(\"\\n📱 Para compartir por WhatsApp:\")\n",
    "    print(\"1. La página se abrirá automáticamente en tu navegador\")\n",
    "    print(\"2. Copia la URL: http://localhost:8000/stitch_love.html\")\n",
    "    print(\"3. Comparte esta URL por WhatsApp\")\n",
    "    print(\"\\n⚠️  IMPORTANTE: El servidor debe estar ejecutándose para que funcione\")\n",
    "    print(\"💡 Presiona Ctrl+C para detener el servidor\")\n",
    "    \n",
    "    try:\n",
    "        # Mantener el servidor activo\n",
    "        while True:\n",
    "            pass\n",
    "    except KeyboardInterrupt:\n",
    "        print(\"\\n🛑 Servidor detenido\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "131de381-c523-4e20-bdea-1900110ad0e3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
